apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeazuresqldbs.database.example.org
spec:
  group: database.example.org
  names:
    kind: CompositeAzureSQLDatabase
    plural: compositeazuresqldbs
  claimNames:
    kind: AzureSQLDatabase
    plural: azuresqldatabases
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    databaseName:
                      type: string
                    maxSizeGB:
                      type: integer
                      default: 5