apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsql-database
spec:
  group: database.example.org
  names:
    kind: xsql
    plural: xsqls
  claimNames:
    kind: azuresql
    plural: azuresqls
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    databaseName:
                      type: string
                    maxSizeGB:
                      type: integer
                      default: 5