apiVersion: sql.azure.upbound.io/v1beta1
kind: MSSQLServer
metadata:
  name: example-sqlserver
spec:
  forProvider:
    administratorLogin: 4dm1n157r470r
    administratorLoginPasswordSecretRef:
      name: sql-password
      key: password
      namespace: crossplane-system
    location: West Europe
    resourceGroupName: example-rg
    version: "12.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-password
  namespace: crossplane-system
type: Opaque
data:
  password: <base64-encoded-password>
---
apiVersion: sql.azure.upbound.io/v1beta1
kind: MSSQLDatabase
metadata:
  name: example-sqldatabase
spec:
  forProvider:
    resourceGroupName: example-rg
    serverName: example-sqlserver
    maxSizeGB: 10
    sku:
      name: S0