apiVersion: sql.azure.upbound.io/v1beta1
kind: MSSQLDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta1/mssqldatabaseextendedauditingpolicy
  labels:
    testing.upbound.io/example-name: example
  name: database
spec:
  forProvider:
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example