apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azuresql-db-composition
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: Xsql
  resources:
    # - name: admin-password
    #   base:
    #     apiVersion: iam.aws.upbound.io/v1beta1
    #     kind: AccessKey
    #     spec:
    #       forProvider:
    #         # Removed for brevity
    #       writeConnectionSecretToRef:
    #         namespace: crossplane-system
    #         name: my-secret
    - name: resource-group
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceGroup
        metadata:
          annotations: 
            crossplane.io/external-name: example-rg
        spec:
          forProvider:
            location: East US
          providerConfigRef:
            name: default
    - name: sqlserver
      base:
        apiVersion: sql.azure.upbound.io/v1beta1
        kind: MSSQLServer
        metadata:
          annotations: 
            crossplane.io/external-name: arsen-sqlserver-2025
          labels:
            testing.upbound.io/example-name: arsen-test-srv
        spec:
          forProvider:
            administratorLogin: myadmin
            administratorLoginPasswordSecretRef:
              name: sql-password
              key: password
              namespace: crossplane-system
            location: East US
            resourceGroupName: "example-rg"
            version: "12.0"
          providerConfigRef:
            name: default
    - name: sqldatabase
      base:
        apiVersion: sql.azure.upbound.io/v1beta1
        kind: MSSQLDatabase
        spec:
          forProvider:
            sku:
              name: S0
            serverIdSelector:
              matchLabels:
                testing.upbound.io/example-name: arsen-test-srv
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.parameters.databaseName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.parameters.maxSizeGB"
          toFieldPath: "spec.forProvider.maxSizeGB"