# argo-cd/crossplane-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/arsenaid/argo-autopilot/apps'
    targetRevision: HEAD
    path: 'crossplane/base'
    helm:
      valueFiles:
        - values.yaml  # Reference the Helm values file
      releaseName: crossplane
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true